.config/nvim/autoload/plug.vim:
  type: file
  url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  refreshPeriod: 672h
.config/awesome/awesome-wm-widgets:
  type: archive
  url: https://github.com/streetturtle/awesome-wm-widgets/archive/refs/heads/master.zip
  exact: true
  stripComponents: 1
  refreshPeriod: 672h
