#!/bin/sh
hooks=$(git rev-parse --git-path hooks)
${hooks}/ctags >/dev/null 2>&1 &
if [ "$3" -eq 1 ]; then
	if [ "$1" = "0000000000000000000000000000000000000000" ]; then
		# A null pre-checkout means we're in a clone or worktree
		ln -s venv .venv # allow poetry to accerss the sharedinfra venv
		make init
	fi
	# Newwer support  || Older support
	make venv-install || make install-dev
fi
