#!/bin/sh
hooks=$(git rev-parse --git-path hooks)
${hooks}/ctags >/dev/null 2>&1 &
if [ "$3" -eq 1 ]; then
	if [ "$1" -eq 0 ]; then
		# A null pre-checkout means we're in a clone or worktree
		make init
	fi
	make install-dev
fi
