#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
tmpfile=".tags.$$"
trap 'rm -f "$tmpfile"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$tmpfile" --languages=-javascript,sql
mv "$tmpfile" ".tags"
